resources:
  - name: Pipeline_Testing
    type: GitRepo
    configuration:
      gitProvider: DockerBuildImagePipeline                       # <-- replace with your integration
      path: Aayush-sood94/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: pipeline_testing_image
    type: Image
    configuration:
      registry:  art                               # <-- replace with your artifactory integration
      sourceRepository: docker-test-local               # <-- required if registry is Artifactory
      imageName: lorelic2.jfrog.io/artifactory/docker-test-local/aayush  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: pipeline_testing_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art 
      buildName: pipeline_testing_build
      buildNumber: 1    

  - name: pipeline_testing_promoted_build_info
    type: BuildInfo
    configuration: 
        sourceArtifactory: art
        buildName: pipeline_testing_build
        buildNumber: 1
pipelines:
  - name: pipeline_testing
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: together
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: lorelic2.jfrog.io/artifactory/docker-test-local/aayush   # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: pipeline_testing
          integrations:
            - name: art                            # <-- replace with your Artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: together
          targetRepository: docker-test-local
          integrations:
            - name: art                            # <-- replace with your Artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: pipeline_testing_image

      - name: publish_pipeline
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: pipeline_testing_build_info

      - name: promote_pipeline
        type: PromoteBuild
        configuration:
          targetRepository: demo-pipelines
          integrations:
            - name: art
          inputResources:
            - name: pipeline_testing_build_info
          outputResources:
            - name: pipeline_testing_promoted_build_info

